[package]
org = "somap"
name = "mongodb_atlas_app"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.3"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.10.3"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.10.4"

[[dependency]]
org = "ballerina"
name = "url"
version = "2.4.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.7.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"

[[dependency]]
org = "ballerina"
name = "email"
version = "2.8.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.6.0"

[[dependency]]
org = "ballerina"
name = "websocket"
version = "2.10.3"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.6.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "4.2.0"

[tool.test]
includes = ["**/*_test.bal"]